# NOTE: This docker-compose.yml is an example setup.
# It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.
# See https://listmonk.app/docs/installation/#manual-docker-install_1

x-app-defaults: &app-defaults
  restart: unless-stopped
  image: listmonk/listmonk:latest
  ports:
    - "9000:9000"
  networks:
    - listmonk
  environment:
    - TZ=Etc/UTC
    - APP_ADDRESS=${APP_ADDRESS}
    - APP_ADMIN_USERNAME=${APP_ADMIN_USERNAME}
    - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_SSLMODE=${DB_SSLMODE}
    - BD_MAX_OPEN=${DB_MAX_OPEN}
    - BD_MAX_IDLE=${DB_MAX_IDLE}
    - BD_MAX_LIFETIME=${DB_MAX_LIFETIME}

x-db-defaults: &db-defaults
  image: postgres:13-alpine
  ports:
    - "${DB_PORT}:5432"
  networks:
    - listmonk
  environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_DB=${DB_NAME}
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U listmonk"]
    interval: 10s
    timeout: 5s
    retries: 6

services:
  db:
    <<: *db-defaults
    container_name: listmonk_db
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    <<: *app-defaults
    container_name: listmonk_app
    hostname: listmonk.example.com # Recommend using FQDN for hostname
    depends_on:
      - db

  demo-db:
    container_name: listmonk_demo_db
    <<: *db-defaults

  demo-app:
    <<: *app-defaults
    container_name: listmonk_demo_app
    command:
      [
        sh,
        -c,
        "yes | ./listmonk --install --config config-demo.toml && ./listmonk --config config-demo.toml",
      ]
    depends_on:
      - demo-db

networks:
  listmonk:

volumes:
  listmonk-data:
