version: "3"

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - listmonk-dev
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-dev-db
        target: /var/lib/postgresql/data

  front:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-frontend"]
    ports:
      - "8080:8080"
    environment:
      - LISTMONK_API_URL=http://backend:9000
    depends_on:
      - db
    volumes:
      - ../:/app
    networks:
      - listmonk-dev

  backend:
    build:
      context: ../
      dockerfile: dev/app.Dockerfile
    command: ["make", "run-backend-docker"]
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - TZ=Etc/UTC
      - APP_ADDRESS=${APP_ADDRESS}
      - APP_ADMIN_USERNAME=${APP_ADMIN_USERNAME}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - BD_MAX_OPEN=${DB_MAX_OPEN}
      - BD_MAX_IDLE=${DB_MAX_IDLE}
      - BD_MAX_LIFETIME=${DB_MAX_LIFETIME}
    volumes:
      - ../:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    networks:
      - listmonk-dev

volumes:
  listmonk-dev-db:

networks:
  listmonk-dev:
